version: '3'

services:
  database:
    container_name: db
    image: mysql
    restart: unless-stopped
    volumes:
      - ./mysqldata:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=adminpassword
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dbmain
    ports:
      - 3306:3306
  
  web:
    container_name: web
    build: 
      context: .
      dockerfile: apache.dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html/
      - ./apacheconfig:/etc/apache2/sites-available/
    ports:
      - 8000:80

  mysqladmin:
    container_name: mysqladmin
    image: adminer
    ports:
      - 8080:8080
